### ISSUE TITLE
[Help] Adapting oqueue to work with files

### ISSUE THREAD

**Issue by jpmckinney** [dtolnay/oqueue#3]
I've noticed a speed improvement after adapting oqueue to work with files. (I'm writing inside a rayon ParallelIterator. I was previously using a plain `Arc<Mutex<BufWriter>>` around a File, and locking the mutex to write at the end of the closure.)

If you are open to answering questions, I wasn't clear on the logic of this part of the Drop implementation:

```rust
        if let Some(head) = inner.pending.get_mut(0) {
            let _ = inner.writer.print(&head.buffer);
            head.buffer.clear();
        }
```

Why is it not necessary to check whether the front of the queue is `done`?

**Comment by dtolnay** [comment]
It wouldn't still be in the queue if it was `done`.

That is what the loop above the snippet you quoted accomplishes.

**Comment by jpmckinney** [comment]
To rephrase my question: why is it getting print()ed if it isn’t done?

Edit: Ah, I guess it doesn't matter that it's not done (whether some content has been written to the buffer or not). We know that it's the next sequential content to print, so we might as well take this opportunity to write it.

**Comment by jpmckinney** [comment]
In case anyone arrives at oqueue wanting to do something similar for files, here's my solution: https://github.com/open-contracting/cardinal-rs/blob/cc9a9cc4b3f7b87356e1dd0f9decde6e8c480a73/src/queue.rs

My implementation incurs a penalty due to dynamic dispatch. Otherwise, it's quite close, minus all the color and style features.

I got a nice 20-30% time improvement when using this with rayon to parallel process and modify lines from 1GB-9GB JSONL files, compared to using an `Arc<Mutex<BufWriter>>` in the typical way (lock, write, and drop at the end of the rayon closure).
